{
 "title": "Heroku Metrics Dashboard",
 "time": { "from": "now-3d", "to": "now" },
 "panels": [
  {
   "title": "Database Follower Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "follower_lag_commits", "legendFormat": "Commits" }
   ]
  },
  {
   "title": "Dyno Count",
   "type": "timeseries",
   "description": "Count by load_avg_1m",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"})",
     "legendFormat": "Comiru Web"
    },
    {
     "expr": "count(load_avg_1m{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"})",
     "legendFormat": "Comiru Worker"
    },
    {
     "expr": "count(load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"})",
     "legendFormat": "Admin Web"
    },
    {
     "expr": "count(load_avg_1m{source_type=\"dyno\", source=\"worker\", app_id=\"97404377\"})",
     "legendFormat": "Admin Worker"
    }
   ]
  },
  {
   "title": "Log Count Cursor",
   "type": "gauge",
   "description": "percent of max in 30d",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "log_gen_count{log_type=\"email_log\"}/max_over_time(log_gen_count{log_type=\"email_log\"}[30d])",
     "legendFormat": "Email"
    },
    {
     "expr": "log_gen_count{log_type=\"line_log\"}/max_over_time(log_gen_count{log_type=\"line_log\"}[30d])",
     "legendFormat": "Line"
    },
    {
     "expr": "log_gen_count{log_type=\"push_log\"}/max_over_time(log_gen_count{log_type=\"push_log\"}[30d])",
     "legendFormat": "Push"
    },
    {
     "expr": "log_gen_count{log_type=\"operation_log\"}/max_over_time(log_gen_count{log_type=\"operation_log\"}[30d])",
     "legendFormat": "Operation"
    },
    {
     "expr": "log_gen_count{log_type=\"router_log\"}/max_over_time(log_gen_count{log_type=\"router_log\"}[30d])",
     "legendFormat": "Router"
    }
   ]
  },
  {
   "title": "Heroku App Dyno Update Status",
   "type": "timeseries",
   "description": "heroku app dyno update status",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heroku_app_dyno_update_status{log_type=\"release\"}",
     "legendFormat": "Release.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_update_status{log_type=\"scale\"}",
     "legendFormat": "Scale.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_update_status{log_type=\"cycling\"}",
     "legendFormat": "Cycling.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_update_status{log_type=\"restart\"}",
     "legendFormat": "Restart.{{app_name}}"
    }
   ]
  },
  {
   "title": "Heroku App Dyno Router Latency",
   "type": "timeseries",
   "description": "heroku app dyno router latency",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heroku_app_dyno_router_latency{log_type=\"p95\"}",
     "legendFormat": "P95.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_latency{log_type=\"p99\"}",
     "legendFormat": "P99.{{app_name}}"
    }
   ]
  },
  {
   "title": "Heroku App Dyno Router Status",
   "type": "timeseries",
   "description": "heroku app dyno router status",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"200\"}",
     "legendFormat": "200.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"204\"}",
     "legendFormat": "204.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"206\"}",
     "legendFormat": "206.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"301\"}",
     "legendFormat": "301.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"302\"}",
     "legendFormat": "302.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"304\"}",
     "legendFormat": "304.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"400\"}",
     "legendFormat": "400.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"403\"}",
     "legendFormat": "403.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"404\"}",
     "legendFormat": "404.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"405\"}",
     "legendFormat": "405.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"414\"}",
     "legendFormat": "414.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"422\"}",
     "legendFormat": "422.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"499\"}",
     "legendFormat": "499.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"500\"}",
     "legendFormat": "500.{{app_name}}"
    },
    {
     "expr": "heroku_app_dyno_router_status{log_type=\"503\"}",
     "legendFormat": "503.{{app_name}}"
    }
   ]
  },
  {
   "title": "Heroku DB Lock Status",
   "type": "timeseries",
   "description": "heroku db lock status",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heroku_db_lock_status", "legendFormat": "Heroku DB Lock Status" }
   ]
  },
  {
   "title": "Comiru Load",
   "type": "gauge",
   "description": "percent of max in 30d",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}/max_over_time(load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}[30d])",
     "legendFormat": "Web.{{exported_instance}}[1m]"
    },
    {
     "expr": "load_avg_5m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}/max_over_time(load_avg_5m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}[30d])",
     "legendFormat": "Web.{{exported_instance}}[5m]"
    },
    {
     "expr": "load_avg_15m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}/max_over_time(load_avg_15m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}[30d])",
     "legendFormat": "Web.{{exported_instance}}[15m]"
    }
   ]
  },
  {
   "title": "Admin Load",
   "type": "gauge",
   "description": "percent of max in 30d",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}/max_over_time(load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}[30d])",
     "legendFormat": "Web.{{exported_instance}}[1m]"
    },
    {
     "expr": "load_avg_5m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}/max_over_time(load_avg_5m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}[30d])",
     "legendFormat": "Web.{{exported_instance}}[5m]"
    },
    {
     "expr": "load_avg_15m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}/max_over_time(load_avg_15m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}[30d])",
     "legendFormat": "Web.{{exported_instance}}[15m]"
    }
   ]
  },
  {
   "title": "Redis Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "active_connections{source=\"REDIS\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "active_connections{source=\"DATABASE\"}",
     "legendFormat": "Leader Active"
    },
    {
     "expr": "active_connections{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower Active"
    },
    {
     "expr": "waiting_connections{source=\"DATABASE\"}",
     "legendFormat": "Leader Waiting"
    },
    {
     "expr": "waiting_connections{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower Waiting"
    }
   ]
  },
  {
   "title": "Router / Operation Log Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "log_gen_count{log_type=\"operation_log\"}",
     "legendFormat": "Operation Count"
    },
    {
     "expr": "log_gen_count{log_type=\"router_log\"}",
     "legendFormat": "Router Count"
    },
    {
     "expr": "max(max_over_time(log_gen_count{log_type=\"operation_log\"}[30d]))",
     "legendFormat": "Operation Max"
    },
    {
     "expr": "max(max_over_time(log_gen_count{log_type=\"router_log\"}[30d]))",
     "legendFormat": "Router Max"
    }
   ]
  },
  {
   "title": "Notification Log Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "log_gen_count{log_type=\"push_log\"}",
     "legendFormat": "Push Count"
    },
    {
     "expr": "log_gen_count{log_type=\"line_log\"}",
     "legendFormat": "Line Count"
    },
    {
     "expr": "log_gen_count{log_type=\"email_log\"}",
     "legendFormat": "Email Count"
    },
    {
     "expr": "max(max_over_time(log_gen_count{log_type=\"push_log\"}[30d]))",
     "legendFormat": "Push Max"
    },
    {
     "expr": "max(max_over_time(log_gen_count{log_type=\"line_log\"}[30d]))",
     "legendFormat": "Line Max"
    },
    {
     "expr": "max(max_over_time(log_gen_count{log_type=\"email_log\"}[30d]))",
     "legendFormat": "Email Max"
    }
   ]
  },
  {
   "title": "Redis Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "load_avg_1m{source=\"REDIS\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "load_avg_5m{source=\"REDIS\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "load_avg_15m{source=\"REDIS\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Database Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "load_avg_1m{source=\"DATABASE\"}",
     "legendFormat": "Leader 1m"
    },
    {
     "expr": "load_avg_5m{source=\"DATABASE\"}",
     "legendFormat": "Leader 5m"
    },
    {
     "expr": "load_avg_15m{source=\"DATABASE\"}",
     "legendFormat": "Leader 15m"
    },
    {
     "expr": "load_avg_1m{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower 1m"
    },
    {
     "expr": "load_avg_5m{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower 5m"
    },
    {
     "expr": "load_avg_15m{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower 15m"
    }
   ]
  },
  {
   "title": "Comiru Load With Dyno Id",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}",
     "legendFormat": "web.{{exported_instance}}[{{dyno_id}}]"
    }
   ]
  },
  {
   "title": "Redis Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_redis{source=\"REDIS\"}",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Database Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "memory_total{source=\"DATABASE\"}-memory_free{source=\"DATABASE\"}",
     "legendFormat": "Leader Usage"
    },
    {
     "expr": "memory_total{source=\"DATABASE_RO\"}-memory_free{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower Usage"
    }
   ]
  },
  {
   "title": "Comiru Web Dyno Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "max(load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}) by (exported_instance)",
     "legendFormat": "Web.{{exported_instance}}[1m]"
    },
    {
     "expr": "max(load_avg_5m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}) by (exported_instance)",
     "legendFormat": "Web.{{exported_instance}}[5m]"
    },
    {
     "expr": "max(load_avg_15m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}) by (exported_instance)",
     "legendFormat": "Web.{{exported_instance}}[15m]"
    },
    {
     "expr": "max(max_over_time(load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}[30d]))",
     "legendFormat": "Max[1m]"
    },
    {
     "expr": "max(max_over_time(load_avg_5m{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}[30d]))",
     "legendFormat": "Max[5m]"
    },
    { "legendFormat": "Max[15m]" }
   ]
  },
  {
   "title": "Comiru Worker Dyno Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "max(load_avg_1m{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"}) by (exported_instance)",
     "legendFormat": "Worker.{{exported_instance}}[1m]"
    },
    {
     "expr": "max(load_avg_5m{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"}) by (exported_instance)",
     "legendFormat": "Worker.{{exported_instance}}[5m]"
    },
    {
     "expr": "max(load_avg_15m{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"}) by (exported_instance)",
     "legendFormat": "Worker.{{exported_instance}}[15m]"
    },
    {
     "expr": "max(max_over_time(load_avg_1m{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"}[30d]))",
     "legendFormat": "Max[1m]"
    },
    {
     "expr": "max(max_over_time(load_avg_5m{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"}[30d]))",
     "legendFormat": "Max[5m]"
    },
    {
     "expr": "max(max_over_time(load_avg_15m{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"}[30d]))",
     "legendFormat": "Max[15m]"
    }
   ]
  },
  {
   "title": "Redis Hit-Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hit_rate{source=\"REDIS\"}",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Database Cache Hit-Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "index_cache_hit_rate{source=\"DATABASE\"}",
     "legendFormat": "Leader Rate"
    },
    {
     "expr": "index_cache_hit_rate{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower"
    }
   ]
  },
  {
   "title": "Comiru Web Dyno Mem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "max(memory_total{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}) by (exported_instance)",
     "legendFormat": "Web.{{exported_instance}}"
    },
    {
     "expr": "max(max_over_time(memory_total{source_type=\"dyno\", source=\"web\", app_id=\"36946693\"}[30d])  )",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Comiru Worker Dyno Mem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "max(memory_total{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"}) by (exported_instance)",
     "legendFormat": "Worker.{{exported_instance}}"
    },
    {
     "expr": "max(max_over_time(memory_total{source_type=\"dyno\", source=\"worker\", app_id=\"36946693\"}[30d]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Redis IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "write_iops{source=\"REDIS\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "read_iops{source=\"REDIS\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Database IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "write_iops{source=\"DATABASE\"}",
     "legendFormat": "Leader write"
    },
    {
     "expr": "write_iops{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower write"
    },
    {
     "expr": "read_iops{source=\"DATABASE\"}",
     "legendFormat": "Leader read"
    },
    {
     "expr": "read_iops{source=\"DATABASE_RO\"}",
     "legendFormat": "Follower read"
    }
   ]
  },
  {
   "title": "Admin Load With Dyno Id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}",
     "legendFormat": "web.{{exported_instance}}[{{dyno_id}}]"
    }
   ]
  },
  {
   "title": "Redis Evicted Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "evicted_keys{source=\"REDIS\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "db_size{source=\"DATABASE\"}",
     "legendFormat": "Leader"
    },
    {
     "expr": "db_size{source=\"HEROKU_POSTGRESQL_BLACK\"}",
     "legendFormat": "Follower"
    }
   ]
  },
  {
   "title": "Admin Web Dyno Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "max(load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}) by (exported_instance)",
     "legendFormat": "Web.{{exported_instance}}[1m]"
    },
    {
     "expr": "max(load_avg_5m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}) by (exported_instance)",
     "legendFormat": "Web.{{exported_instance}}[5m]"
    },
    {
     "expr": "max(load_avg_15m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}) by (exported_instance)",
     "legendFormat": "Web.{{exported_instance}}[15m]"
    },
    {
     "expr": "max(max_over_time(load_avg_1m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}[30d]))",
     "legendFormat": "Max[1m]"
    },
    {
     "expr": "max(max_over_time(load_avg_5m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}[30d]))",
     "legendFormat": "Max[5m]"
    },
    {
     "expr": "max(max_over_time(load_avg_15m{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}[30d]))",
     "legendFormat": "Max[15m]"
    }
   ]
  },
  {
   "title": "Admin Web Dyno Mem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "targets": [
    {
     "expr": "max(memory_total{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}) by (exported_instance)",
     "legendFormat": "Web.{{exported_instance}}"
    },
    {
     "expr": "max(max_over_time(memory_total{source_type=\"dyno\", source=\"web\", app_id=\"97404377\"}[30d])  )",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Admin Worker Dyno Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "load_avg_1m{source_type=\"dyno\", source=\"worker\", app_id=\"97404377\"}",
     "legendFormat": "Worker.{{exported_instance}}[1m]"
    },
    {
     "expr": "load_avg_5m{source_type=\"dyno\", source=\"worker\", app_id=\"97404377\"}",
     "legendFormat": "Worker.{{exported_instance}}[5m]"
    },
    {
     "expr": "load_avg_15m{source_type=\"dyno\", source=\"worker\", app_id=\"97404377\"}",
     "legendFormat": "Worker.{{exported_instance}}[15m]"
    }
   ]
  },
  {
   "title": "Admin Worker Dyno Mem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "targets": [
    {
     "expr": "memory_total{source_type=\"dyno\", source=\"worker\", app_id=\"97404377\"}",
     "legendFormat": "Worker.{{exported_instance}}"
    },
    {
     "expr": "max(memory_quota{source_type=\"dyno\", source=\"worker\", app_id=\"97404377\",exported_instance=\"1\"})",
     "legendFormat": "Quota"
    }
   ]
  }
 ]
}