{
 "title": "System Monitoring",
 "tags": [ "alerts" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Free Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Virtual Mem Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Free Memory (RAM + Swap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes + node_memory_SwapFree_bytes)/(node_memory_MemTotal_bytes + node_memory_SwapTotal_bytes)*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/rootfs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}